# Zoo classifier (TF 2.x 버전)

https://github.com/hunkim/DeepLearningZeroToAll/blob/master/tf2/tf2-06-2-softmax_zoo_classifier.py


In [ ]:
# for yhlee macbook
# %pip install tensorflow==2.16.2 tensorflow-metal==1.2.0

In [ ]:
# %pip install tensorflow

In [1]:
# Lab 6 Softmax Classifier

import tensorflow as tf
import numpy as np

/Users/yhlee/work/ai/ml_study/l-regen/.venv/lib/python3.11/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [4]:

# Predicting animal type based on various features
xy = np.loadtxt('data/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

# (101, 16) (101, 1)


(101, 16) (101, 1)


In [6]:

nb_classes = 7  # 0 ~ 6

# Convert y_data to one_hot
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:", y_one_hot[:5])



one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


In [9]:

tf.model = tf.keras.Sequential()

tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=16, activation='softmax'))


/Users/yhlee/work/ai/ml_study/l-regen/.venv/lib/python3.11/site-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:

# tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
# 이 코드는 에러 발생시킴
# ValueError: Argument(s) not recognized: {'lr': 0.1}
# 예전에는 lr 이라는 약식 이름을 허용했으나 지금 최신 버전들에서는 제대로 이름을 지정하도록 바뀜.

tf.model.compile(loss='categorical_crossentropy',
    # optimizer=tf.keras.optimizers.SGD(lr=0.1),
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
    metrics=['accuracy'])

In [11]:
tf.model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 7)              │           119 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 119 (476.00 B)

 Trainable params: 119 (476.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:

history = tf.model.fit(x_data, y_one_hot, epochs=1000)

In [13]:

# Single data test
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]]) # expected prediction == 3 (feathers)
print(tf.model.predict(test_data), np.argmax(tf.model.predict(test_data), axis=-1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[[8.0519356e-04 1.2511984e-03 7.2893212e-03 9.8453575e-01 4.1097286e-03
  6.8493415e-07 2.0080793e-03]] [3]
